# rectangle formation yaml
# global goal setting
global_goal:
  swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 2.0
  relative_pos_S0 : {x: 0.0, y: 0.0, z: 0.0}  
  relative_pos_S1 : {x: 1.7321, y: -1.0, z: 0.0}
  relative_pos_S2 : {x: 0.0, y: -2.0, z: 0.0}
  relative_pos_S3 : {x: -1.7321, y: -1.0, z: 0.0} 
  relative_pos_S4 : {x: -1.7321, y: 1.0, z: 0.0}
  relative_pos_S5 : {x: 0.0, y: 2.0, z: 0.0}
  relative_pos_S6 : {x: 1.7321, y: 1.0, z: 0.0} 

  relative_pos_Y0 : {x: 0.0, y: 0.0, z: 0.0}  
  relative_pos_Y1 : {x: 1.414, y: -1.414, z: 0.0} 
  relative_pos_Y2 : {x: 2.828, y: -2.828, z: 0.0} 
  relative_pos_Y3 : {x: -2.828, y: -2.828, z: 0.0}  
  relative_pos_Y4 : {x: -1.414, y: -1.414.0, z: 0.0}
  relative_pos_Y5 : {x: 0.0, y: 4.0, z: 0.0}
  relative_pos_Y6 : {x: 0.0, y: 2.0, z: 0.0}

  relative_pos_U0 : {x: 0.0, y: 2.0, z: 0.0}  
  relative_pos_U1 : {x: 1.8, y: 1.3, z: 0.0} 
  relative_pos_U2 : {x: 2.0, y: -0.0, z: 0.0} 
  relative_pos_U3 : {x: 2.0, y: -2.0, z: 0.0}  
  relative_pos_U4 : {x: -1.8, y: 1.3, z: 0.0}
  relative_pos_U5 : {x: -2.0, y: -0.0, z: 0.0}
  relative_pos_U6 : {x: -2.0, y: -2.0, z: 0.0}

# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  formation_type      : 1
  weight_obstacle     : 50000.0
  weight_swarm        : 50000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 80.0
  weight_formation    : 15000.0
  obstacle_clearance  : 0.5
  swarm_clearance     : 0.5

fsm:
  replan_trajectory_time : 0.1    # s, the max time of replanning trajectory
  playmode            : 1